# Generated by Django 4.2.13 on 2024-07-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_access_manysystem_manylocation_manybranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manybranch',
            name='access',
        ),
        migrations.RemoveField(
            model_name='manybranch',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='manylocation',
            name='access',
        ),
        migrations.RemoveField(
            model_name='manylocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='manysystem',
            name='access',
        ),
        migrations.RemoveField(
            model_name='manysystem',
            name='system',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
        migrations.DeleteModel(
            name='ManyBranch',
        ),
        migrations.DeleteModel(
            name='ManyLocation',
        ),
        migrations.DeleteModel(
            name='ManySystem',
        ),
    ]
